Translate conventions folder
crystal-tw/docs pull request #10
Opened 2020-05-16 21:50 UTC by imo-ininder

2020-05-16 22:05 UTC, david50407 commented on conventions/README.md
> +* 閱讀並使用 [標準 coding style](coding_style.md) 讓我們的專案能夠有更高的可讀性和可導航性。
Coding Style 大寫

2020-05-16 22:05 UTC, david50407 commented on conventions/README.md
> +* 撰寫 [文件](documenting_code.md) 來表達我們程式的目的並且讓 `crystal docs` 能夠自動產出文件。
「撰寫文件來表達」 中間不用空格

2020-05-16 22:05 UTC, david50407 commented on conventions/README.md
> +* 撰寫 [文件](documenting_code.md) 來表達我們程式的目的並且讓 `crystal docs` 能夠自動產出文件。
條列式不加句號

2020-05-16 22:08 UTC, david50407 commented on conventions/coding_style.md
> +__型別名稱__ 使用駝峰式命名。 範例:
不加空格或用冒號或破折號

2020-05-16 22:09 UTC, david50407 commented on conventions/coding_style.md
> +__型別名稱__ 使用駝峰式命名。 範例:
標點符號全形

2020-05-16 22:10 UTC, david50407 commented on conventions/coding_style.md
> +`函式庫` 命名皆須以 `Lib` 為前綴。 如: `LibC`、`LibEvent2`。
函式庫不加 `\``

2020-05-16 22:22 UTC, david50407 commented on conventions/documenting_code.md
> +Crystal 能夠使用那些符合 [Markdown](https://daringfireball.net/projects/markdown/) 語法的註解自動產生文件。
subset 子集

2020-05-16 22:23 UTC, david50407 commented on conventions/documenting_code.md
> +如果想要產生一個專案的文件，你可以使用`crystal docs`指令。在預設的情況下，會在`docs`目錄下產生`index.html`作為專案文件的進入點。請參閱 [Using the compiler – Creating documentation](../using_the_compiler/#crystal-docs)。
空格

2020-05-16 22:23 UTC, david50407 commented on conventions/documenting_code.md
> +# 獨角獸是一種 **傳說生物** （請參閱 `傳說` 模組） 自古以來
Legendary 模組

2020-05-16 22:26 UTC, david50407 commented on conventions/documenting_code.md
> +Crystal 內建的 code formatter 不僅僅只能用來 format 我們的程式碼，它還能用來 format 文件區塊中的範例程式碼。
format 格式化

2020-05-16 22:34 UTC, davy-tw requested changes

2020-05-16 22:34 UTC, david50407 commented on conventions/README.md
> +* 撰寫 [文件](documenting_code.md) 來表達我們程式的目的並且讓 `crystal docs` 能夠自動產出文件
撰寫[文件]來表達

不需要加空格

2020-05-16 22:34 UTC, david50407 commented on conventions/README.md
> +* 閱讀並使用 [標準 Coding Style](coding_style.md) 讓我們的專案能夠有更高的可讀性和可導航性
使用標準

不需要空格

2020-05-16 22:34 UTC, david50407 commented on conventions/coding_style.md
> +類別名稱中縮寫，使用**全大寫**。 如， `HTTP` 、 `LibXML`。
，`HTTP`、

標點符號及英文字母之間不用空格

2020-05-16 22:34 UTC, david50407 commented on conventions/coding_style.md
> +- `/` 包含 readme, 與專案相關的所有設定檔 （例如, CI 設定 或者 編輯器設定）， 以及所有是專案層級的相關文件 （例如， 更新日誌 或 contributing guide）
readme -> 說明文件

2020-05-16 22:34 UTC, david50407 commented on conventions/coding_style.md
> +- `/` 包含 readme, 與專案相關的所有設定檔 （例如, CI 設定 或者 編輯器設定）， 以及所有是專案層級的相關文件 （例如， 更新日誌 或 contributing guide）
例如 CI 設定

不加奇怪的逗號

2020-05-16 22:34 UTC, david50407 commented on conventions/coding_style.md
> +- `/` 包含 readme, 與專案相關的所有設定檔 （例如, CI 設定 或者 編輯器設定）， 以及所有是專案層級的相關文件 （例如， 更新日誌 或 contributing guide）
更新日誌或

不加空白

2020-05-16 22:35 UTC, david50407 commented on conventions/documenting_code.md
> +# 獨角獸是一種 **傳說生物** （請參閱 `Legendary` 模組） 自古以來
中文之間不加空格

2020-05-16 22:38 UTC, david50407 commented on conventions/documenting_code.md
> +# 不良示範: 這將不會被附加在任何的類別上.
全形句號

2020-05-16 22:38 UTC, david50407 commented on conventions/documenting_code.md
> +* 關於方法的說明包含兩個部分，其一是方法的簡介，另一個則是方法的細節。簡介應該且只能有一行，而後者包含了這個方法剩下的所有說明。簡而言之：
上面空一行

2020-05-16 22:38 UTC, david50407 commented on conventions/documenting_code.md
> +* （在英文中） 使用第三人稱視角描述: `(This mtehod) Returns the number of horns this unicorn has` 而不是 `(I, We) Return the number of horns this unicorn has`。
） 右邊不加空格

2020-05-16 22:39 UTC, david50407 commented on conventions/documenting_code.md
> +* 文字區塊，如範例輸出，應該由 "text" 關鍵字作為開頭且被三個重音符（backtick）包圍。
改用 `

2020-05-16 22:40 UTC, david50407 commented on conventions/documenting_code.md
> +### 標示（Flagging） 類別、模組與方法
）右邊不加空格

2020-05-16 22:40 UTC, davy-tw requested changes

2020-05-16 22:40 UTC, david50407 commented on conventions/documenting_code.md
> +> **注意:** 文件的繼承只能作用於非建構子的方法上。
全形：

2020-05-16 22:41 UTC, david50407 commented on conventions/documenting_code.md
> +的標示（flag）關鍵字必須要是每一行的第一個字，並且必須是大寫。而結尾的逗號或分號是可選的，它們的存在通常是為了提高可讀性。
的？

2020-05-16 22:41 UTC, david50407 commented on conventions/documenting_code.md
> +此外Crystal formatter 非常的快，所以格式化單一個檔案與格式化整個專案時間上並沒有太大的差別。
空格

2020-05-16 22:42 UTC, david50407 commented on conventions/documenting_code.md
> +# 上面的操作將會產生:
：

2020-05-16 22:42 UTC, david50407 commented on conventions/documenting_code.md
> +  # 創造一支獨角獸，讓它有特定數量的 *角*
減少空格

2020-05-17 04:20 UTC, david50407 commented on conventions/coding_style.md
> +類別名稱中縮寫，使用**全大寫**。 如， `HTTP`、`LibXML`。
如，`HTTP`

逗號後面不需要空格

2020-05-17 04:20 UTC, david50407 commented on conventions/coding_style.md
> +類別名稱中縮寫，使用**全大寫**。 如， `HTTP`、`LibXML`。
甚至不需要那個逗號

2020-05-17 04:21 UTC, david50407 commented on conventions/coding_style.md
> +方法名稱中縮寫，使用**全小寫**。  如 `#from_json`、`#to_io`。
。 句號後面不需要空到兩個

2020-05-17 04:21 UTC, david50407 commented on conventions/coding_style.md
> +路徑會依照該檔案的命名空間（namespace）分類，而檔名則會以**小寫底線分隔**方式表達該檔案所定義的類（class）或子命名空間（namespace）。
類 -> 類別

2020-05-17 04:39 UTC, david50407 commented on conventions/coding_style.md
> +例如， `HTTP::WebSocket` 應該被定義於 `src/http/web_socket.cr` 之中。
逗號跟英文之間不加空格

2020-05-17 04:40 UTC, david50407 commented on conventions/documenting_code.md
> +Crystal 能夠使用那些符合部分的 [Markdown](https://daringfireball.net/projects/markdown/) 語法的註解自動產生文件。
「能夠使用部分的 Markdown 語法」即可

2020-05-17 04:40 UTC, david50407 commented on conventions/documenting_code.md
> +# 不良示範: 這將不會被附加在任何的類別上。
全形：

2020-05-17 04:41 UTC, david50407 commented on conventions/documenting_code.md
> +# 創造一支獨角獸，讓它有特定數量的 *角*。
中文中間不空格

2020-05-17 04:42 UTC, david50407 commented on conventions/documenting_code.md
> +* 如果想要自動連結到同一份文件中的方法，使用像是 `#horns` 或是 `#index(char)` ，並將其以一個重音符（backtick）包圍。
英文跟全形標點之間不空格

2020-05-17 04:42 UTC, david50407 commented on conventions/documenting_code.md
> +* 如果想要自動連結到不同型別的方法，使用 `OtherType#method(arg1, arg2)` 或是 `OtherType#method` ，並將其以一個重音符（backtick）包圍。
英文跟全形標點之間不空格

2020-05-17 04:42 UTC, david50407 commented on conventions/documenting_code.md
> +範例:
全形：

2020-05-17 04:43 UTC, david50407 commented on conventions/documenting_code.md
> +而 `Unicorn#name` 的文件將會是：
文件 -> 說明

這邊這樣改會不會比較好？

2020-05-17 04:44 UTC, david50407 commented on conventions/documenting_code.md
> +在註解中使用合法的關鍵字， Crystal 將會自動地生成視覺化的標示，用來標示問題（problems）、註記（notes）或者是潛在的問題（possible issues）。
英文跟全形標點之間不空格

2020-05-17 04:44 UTC, david50407 commented on conventions/documenting_code.md
> +此外 Crystal formatter 非常的快，所以格式化單一個檔案與格式化整個專案時間上並沒有太大的差別。
此外，

加個逗號？

2020-05-17 04:45 UTC, david50407 commented on conventions/documenting_code.md
> +  # 創造一支獨角獸，讓它有特定數量的 *角*
中文之間不空格

2020-05-17 04:45 UTC, david50407 commented on conventions/documenting_code.md
> +  # 回傳這隻獨角獸有幾隻角。
拿掉句號

2020-05-17 13:10 UTC, imo-ininder commented on conventions/documenting_code.md
> +而 `Unicorn#name` 的文件將會是：
用說明文件好了

2020-05-17 13:25 UTC, david50407 commented
LGTM。 先 squash commits 吧

2020-05-17 13:37 UTC, merged